version: "3.3"
services:
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "27017:27017"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "crud_app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    ports:
      - "5432:5432"



