eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
server:
  port: 0
spring:
  application:
    name:
      consumer-app
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users_requests
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: user.queue
    routing-key: user.routingKey


